[deps]
Bcube = "cf06320b-b7f3-4748-8003-81a6b6979792"
BcubeGmsh = "8c8b3700-392b-4630-b974-b8b78831232a"
BcubeVTK = "f7a61acb-f482-4505-b2eb-e9cadd76b6b4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
