[deps]
Bcube = "cf06320b-b7f3-4748-8003-81a6b6979792"
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BcubeGmsh = "8c8b3700-392b-4630-b974-b8b78831232a"
BcubeVTK = "f7a61acb-f482-4505-b2eb-e9cadd76b6b4"

[compat]
Bcube = "0.2, 0.3"
